### ISSUE TITLE
Pug support

### ISSUE THREAD

**Issue by luminarious** [saberland/saber#5]
I added `pug` and `pug-loader` packages, but unlike Vuepress this didn't enable Pug templating. What can I do?

**Comment by egoist** [comment]
I haven't added built-it pug support for Saber.js, but it should follow this guide: https://vue-loader.vuejs.org/guide/pre-processors.html#pug

**Comment by egoist** [comment]
Before we release a new version, you can do:

```js
module.exports = {
  chainWebpack(config) {
    config.module
      .rule('pug')
      .test(/\.pug$/)
      .use('pug-plain-loader')
        .loader('pug-plain-loader')
  }
}
```

To add pug support.

**Comment by luminarious** [comment]
I got an error out of that one:

```
> hello-saber@1.0.0 dev /Users/hardi/Code/hello-saber
> saber dev

TypeError: Cannot read property 'add' of undefined
    at Saber.normalizeOptions (/Users/hardi/Code/hello-saber/node_modules/saber/lib/index.js:60:28)
    at new Saber (/Users/hardi/Code/hello-saber/node_modules/saber/lib/index.js:28:25)
    at module.exports.args (/Users/hardi/Code/hello-saber/node_modules/saber/lib/index.js:358:31)
    at Command.cli.command [as handler] (/Users/hardi/Code/hello-saber/node_modules/saber/bin/cli.js:11:25)
    at Cac.parse (/Users/hardi/Code/hello-saber/node_modules/cac/dist/cac.js:428:35)
    at Object.<anonymous> (/Users/hardi/Code/hello-saber/node_modules/saber/bin/cli.js:27:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

**Comment by egoist** [comment]
It should be fixed in latest version, pug is also supported by default now.
