### ISSUE TITLE
Build requires PostCSS @ 8 support

### ISSUE THREAD

**Issue by andreasvirkus** [saberland/saber#670]
## Bug report

The dev server (`saber`) fails to compile with the message:

```
ERROR in ./node_modules/prismjs/themes/prism-tomorrow.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-3-1!./node_modules/@egoist/postcss-loader/src??ref--5-oneOf-3-2!./node_modules/prismjs/themes/prism-tomorrow.css)
Module build failed (from ./node_modules/@egoist/postcss-loader/src/index.js):
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/anc/code/cottage/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/anc/code/cottage/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/anc/code/cottage/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/anc/code/cottage/node_modules/@egoist/postcss-loader/src/index.js:145:12
 @ ./node_modules/prismjs/themes/prism-tomorrow.css 4:14-154 14:3-18:5 15:22-162
 @ ./saber-browser.js
 @ ./.saber/extend-browser-api.js
 @ ./node_modules/saber/vue-app/create-app.js
 @ ./node_modules/saber/vue-app/entry-client.js
 @ multi ./node_modules/saber/vue-app/entry-client.js
 ```

#### Steps to reproduce

1. Brand new saber project
2. `npm run dev`

#### What is expected?

Saber would compile

#### What is actually happening?

Post CSS complains about not having the minimum required version

#### Other relevant information

- Result of running `saber -v`: `0.11.7`
- Browser version (optional): N/A
- Is Saber a global or local install? Local
- Which package manager did you use for the install? `npm`
- Does this issue occur when all plugins are disabled? Yup

**Comment by andreasvirkus** [comment]
Can we swap out `@egoist/postcss-loader` for the upstream package (https://github.com/webpack-contrib/postcss-loader)? There doesn't seem to be any diff - https://github.com/webpack-contrib/postcss-loader/compare/master...egoist:master

Here's also Post CSS's official migration guide - https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

**Comment by andreasvirkus** [comment]
Downgrading and fixing `autoprefixer` to version `9.8.6` allows to compile Saber currently as a workaround

**Comment by Carrie999** [comment]
![8](https://user-images.githubusercontent.com/26757216/111451709-af1b5380-874c-11eb-86dc-7a11fb4807eb.gif)

**Comment by Carrie999** [comment]
![image](https://user-images.githubusercontent.com/26757216/111596002-ab003c00-8807-11eb-866c-df7a63714580.png)
